# preload = ~/.config/hypr/wallpapers/planet-express.png
# wallpaper = , ~/.config/hypr/wallpapers/planet-express.png

wallpaper {
    monitor = 
    path = ~/.config/hypr/wallpapers/battery_dead_wallpaper.png
    fit_mode = cover
}

# preload = ~/.config/hypr/wallpapers/battery_dead_wallpaper.png
# wallpaper = , ~/.config/hypr/wallpapers/battery_dead_wallpaper.png

